/**
 * Phase 10 — PPTX title slide (D-03, brand-free PPT-02). Factual estate
 * identity + freshness; no client logo, no editorial tagline. Pure
 * engine: no UI framework, no store, no translation runtime — the
 * resolved strings bag is injected.
 */
import type PptxGenJS from 'pptxgenjs'
import type { ExportStrings } from '../../types'
import { type ExportLocale, pptxNumber, pptxSafeFormat } from '../format'
import { PPTX_THEME, SLIDE } from '../theme'

export interface TitleData {
  vcenters: string
  clusterCount: number
  hostCount: number
  vmCount: number
  capturedAt: string
}

export function addTitleSlide(
  pptx: PptxGenJS,
  d: TitleData,
  strings: ExportStrings,
  locale: ExportLocale,
): void {
  const s = pptx.addSlide()
  s.background = { color: PPTX_THEME.bg }
  s.addText(pptxSafeFormat(d.vcenters), {
    ...PPTX_THEME.title,
    x: SLIDE.margin,
    y: 2.2,
    w: SLIDE.w - SLIDE.margin * 2,
    h: 1,
  })
  const identity =
    strings['title.identity'] ??
    `${pptxNumber(d.clusterCount, locale)} clusters · ${pptxNumber(d.hostCount, locale)} hosts · ${pptxNumber(d.vmCount, locale)} VMs · captured ${d.capturedAt}`
  s.addText(pptxSafeFormat(identity), {
    ...PPTX_THEME.body,
    x: SLIDE.margin,
    y: 3.4,
    w: SLIDE.w - SLIDE.margin * 2,
    h: 0.5,
  })
  s.addText(strings['title.generated'] ?? 'Generated by vatlas — factual estate synthesis', {
    ...PPTX_THEME.muted,
    x: SLIDE.margin,
    y: 4.1,
    w: SLIDE.w - SLIDE.margin * 2,
    h: 0.4,
  })
}
