/**
 * Phase 10 — PPTX cover slide (D-03, brand-free PPT-02). Full navy field
 * with a gold factual rule; factual estate identity + freshness; no client
 * logo, no editorial tagline. Pure: strings injected.
 */
import type PptxGenJS from 'pptxgenjs'
import type { ExportStrings } from '../../types'
import { type ExportLocale, pptxNumber, pptxSafeFormat } from '../format'
import { PPTX_COLORS } from '../primitives/colors'
import { SLIDE } from '../theme'

export interface TitleData {
  vcenters: string
  clusterCount: number
  hostCount: number
  vmCount: number
  capturedAt: string
}

export function addTitleSlide(
  pptx: PptxGenJS,
  d: TitleData,
  strings: ExportStrings,
  locale: ExportLocale,
): void {
  const s = pptx.addSlide()
  s.background = { color: PPTX_COLORS.primary500 }
  const M = SLIDE.margin
  const W = SLIDE.w - M * 2

  s.addText(pptxSafeFormat(d.vcenters || 'VMware estate'), {
    x: M,
    y: 2.5,
    w: W,
    h: 1.1,
    color: 'ffffff',
    fontFace: 'Calibri',
    fontSize: 34,
    bold: true,
  })
  // gold factual rule
  s.addShape('rect', {
    x: M,
    y: 3.7,
    w: 2.4,
    h: 0.06,
    fill: { color: PPTX_COLORS.accent },
    line: { type: 'none' },
  })
  const identity =
    strings['title.identity'] ??
    `${pptxNumber(d.clusterCount, locale)} clusters · ${pptxNumber(d.hostCount, locale)} hosts · ${pptxNumber(d.vmCount, locale)} VMs · captured ${d.capturedAt}`
  s.addText(pptxSafeFormat(identity), {
    x: M,
    y: 3.95,
    w: W,
    h: 0.5,
    color: PPTX_COLORS.primary200,
    fontFace: 'Consolas',
    fontSize: 14,
  })
  s.addText(strings['title.generated'] ?? 'Generated by vatlas — factual estate synthesis', {
    x: M,
    y: 6.7,
    w: W,
    h: 0.4,
    color: PPTX_COLORS.primary200,
    fontFace: 'Calibri',
    fontSize: 11,
  })
}
