import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import PptxGenJS from 'pptxgenjs'
import { describe, expect, it } from 'vitest'
import type { FsFillRisk, FsRiskRow } from '@/engines/aggregation/fsFillRisk'
import { bytes, cores, mhz, mib, sockets } from '@/engines/units'
import type { AccountingMode } from '@/types/estate'
import type { GuestRow } from '@/types/guest'
import type { NodeRow } from '@/types/node'
import type {
  ProxmoxBackupJobRow,
  ProxmoxHaResourceRow,
  ProxmoxHaStatusRow,
  ProxmoxSnapshotRow,
  ProxmoxStorageContentRow,
  Snapshot,
} from '@/types/snapshot'
import { buildExportView } from '../buildExportView'
import { buildPptx } from './builder'
import { chartSvgToPng } from './primitives/chartSvg'
import type { ContentionRow } from './slides/contentionAnnex'
import { addFsFillSlide } from './slides/fsFillSlide'

// node-fs wasm bytes for producing a real network PNG (mirrors chartSvg.test).
const require = createRequire(import.meta.url)
const wasmBytes = readFileSync(require.resolve('@resvg/resvg-wasm/index_bg.wasm'))

const TODAY = new Date('2026-01-01T00:00:00Z')
const MODE: AccountingMode = 'configured'
const strings = { 'title.generated': 'Generated by vatlas — factual estate synthesis' }

const vmRow = (c: number): GuestRow => ({
  vmName: `vm-c${c}`,
  cluster: `C${c}`,
  host: `h${c}`,
  vcpu: cores(4),
  vramMib: mib(8192),
  cpuReadinessPercent: null,
  poweredOn: true,
  powerState: 'poweredOn',
  template: false,
  osConfig: 'Ubuntu Linux (64-bit)',
  osTools: '',
  vmBiosUuid: '',
  vmInstanceUuid: '',
  viSdkUuid: '',
  viSdkServer: '',
  guestType: 'qemu',
  provisionedMib: mib(40_960),
  inUseMib: mib(20_480),
  path: '',
})

const hostRow = (c: number): NodeRow => ({
  hostName: `h${c}`,
  cluster: `C${c}`,
  sockets: sockets(2),
  cores: cores(24),
  speedMhz: mhz(2600),
  memoryMib: mib(524_288),
  cpuRatio: 0.4,
  ramRatio: 0.5,
  faultDomain: '',
  model: '',
  vendor: '',
  serialNumber: '',
  esxVersion: '',
})

const snap = (id: string, nClusters: number, capturedAt: Date): Snapshot => ({
  id,
  filename: `${id}.xlsx`,
  fileSize: bytes(1024),
  capturedAt,
  vCenterLabel: 'vc-prod',
  rvtoolsVersion: '4.7.1.4',
  parsedAt: new Date('2026-01-02'),
  source: 'proxmox',
  viSdkUuid: null,
  vMetaData: [],
  guests: Array.from({ length: nClusters }, (_, c) => vmRow(c)),
  nodes: Array.from({ length: nClusters }, (_, c) => hostRow(c)),
  vmUsage: [],
  proxmoxSnapshots: [],
  proxmoxStorageContent: [],
  proxmoxHaResources: [],
  proxmoxHaStatus: [],
  proxmoxBackupJobs: [],
  storages: [],
  vpartition: [],
  nodeInterfaces: [],

  vmNics: [],
  parseErrors: [],
})

/** Count distinct `ppt/slides/slideN.xml` parts in the OOXML zip. Zip
 *  stores entry names in plaintext local/central headers; a Set dedupes
 *  the local-header vs central-dir repeats. */
function slideCount(ab: ArrayBuffer): number {
  const txt = new TextDecoder('latin1').decode(new Uint8Array(ab))
  const m = txt.match(/ppt\/slides\/slide\d+\.xml/g) ?? []
  return new Set(m.map((p) => p.replace(/^.*\//, ''))).size
}

const isZip = (ab: ArrayBuffer): boolean => {
  const u = new Uint8Array(ab)
  return u[0] === 0x50 && u[1] === 0x4b && u[2] === 0x03 && u[3] === 0x04
}

async function renderSlideText(fn: (p: PptxGenJS) => void): Promise<string> {
  const pptx = new PptxGenJS()
  pptx.defineLayout({ name: 'WIDE', width: 13.333, height: 7.5 })
  pptx.layout = 'WIDE'
  fn(pptx)
  const ab = (await pptx.write({ outputType: 'arraybuffer' })) as ArrayBuffer
  return new TextDecoder('latin1').decode(new Uint8Array(ab))
}

const fsRow = (i: number): FsRiskRow => ({
  node: `pve${i % 3}`,
  vmId: String(100 + i),
  vmName: `vm-${i}`,
  vmType: 'qemu',
  mountPoint: `/data${i}`,
  fsType: 'ext4',
  totalGb: 100,
  usedGb: 95,
  usedPct: 95,
  overThreshold: true,
})

const fsRisk = (n: number): FsFillRisk => ({
  overThreshold: Array.from({ length: n }, (_, i) => fsRow(i)),
  overThresholdCount: n,
  totalMounts: n,
  totalVms: n,
  threshold: 0.8,
})

describe('Fix 2 — FS-fill slide remainder footer', () => {
  it('shows the footer when over-threshold rows exceed the cap', async () => {
    const txt = await renderSlideText((p) => addFsFillSlide(p, fsRisk(15), {}, 'en'))
    expect(txt).toContain('more mounts over threshold')
    expect(txt).toContain('+ 3 more') // 15 − 12
  })

  it('omits the footer when rows fit', async () => {
    const txt = await renderSlideText((p) => addFsFillSlide(p, fsRisk(10), {}, 'en'))
    expect(txt).not.toContain('more mounts over threshold')
  })
})

describe('buildPptx — Proxmox label on title slide', () => {
  it('title slide uses the Proxmox cluster label, not a VMware fallback', async () => {
    // Build a snapshot whose single cluster is named 'pve-prod'
    const pveVm: GuestRow = { ...vmRow(0), cluster: 'pve-prod' }
    const pveHost: NodeRow = { ...hostRow(0), cluster: 'pve-prod' }
    const s: Snapshot = {
      ...snap('a', 0, TODAY),
      guests: [pveVm],
      nodes: [pveHost],
    }
    const { view, trends } = buildExportView(s, [s], MODE, TODAY)
    expect(view.clusters[0]?.cluster).toBe('pve-prod')
    const ab = await buildPptx(view, trends, strings, 'en')
    const txt = new TextDecoder('latin1').decode(new Uint8Array(ab))
    expect(txt).toContain('pve-prod')
    expect(txt).not.toMatch(/VMware/i)
  })
})

describe('buildPptx — golden structural snapshot', () => {
  it('emits a valid OOXML container (PK\\x03\\x04) that opens without Repair', async () => {
    const s = snap('a', 3, TODAY)
    const { view, trends } = buildExportView(s, [s], MODE, TODAY)
    const ab = await buildPptx(view, trends, strings, 'en')
    expect(isZip(ab)).toBe(true)
    expect(ab.byteLength).toBeGreaterThan(1000)
  })

  it('fixed PPT-03 order: 5 + clusterCount, +1 trends (≥2 snap), +1 annex', async () => {
    // 1 snapshot, 6 clusters, no trends, no contention
    const a = snap('a', 6, new Date('2026-01-01'))
    const one = buildExportView(a, [a], MODE, TODAY)
    expect(one.trends).toBeNull()
    const abOne = await buildPptx(one.view, one.trends, strings, 'en')
    // title+overview(2) + 6 clusters + storage+network(2) + eos(1)
    // + planned(1) + inventory(1) = 13
    expect(slideCount(abOne)).toBe(13)

    // 2 snapshots ⇒ trends slide present (D-09 satisfied)
    const b = snap('b', 6, new Date('2026-02-01'))
    const two = buildExportView(a, [a, b], MODE, TODAY)
    expect(two.trends).not.toBeNull()
    const abTwo = await buildPptx(two.view, two.trends, strings, 'en')
    expect(slideCount(abTwo)).toBe(14) // +1 trends

    // + conditional contention annex
    const rows: ContentionRow[] = [{ cluster: 'C0', cpuReadyPct: 3.2 }]
    const abAnnex = await buildPptx(two.view, two.trends, strings, 'en', {
      contentionRows: rows,
    })
    expect(slideCount(abAnnex)).toBe(15) // +1 annex
  })

  it('P-RS: a view WITH usage data adds exactly one right-sizing slide', async () => {
    const a = snap('a', 6, new Date('2026-01-01'))
    const withUsage: Snapshot = {
      ...a,
      vmUsage: [
        {
          vmName: 'vm-c0',
          cluster: 'C0',
          vmBiosUuid: '',
          vmInstanceUuid: '',
          activeMib: mib(1024),
          consumedMib: mib(2048),
          balloonedMib: mib(0),
          swappedMib: mib(0),
          cpuUsageMhz: mhz(300),
        },
      ],
    }
    const ex = buildExportView(withUsage, [withUsage], MODE, TODAY)
    expect(ex.sizing.hasUsageData).toBe(true)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(14) // 13 baseline + 1 right-sizing

    // Without usage data the slide is omitted (back to baseline).
    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.sizing.hasUsageData).toBe(false)
    const abNone = await buildPptx(exNone.view, exNone.trends, strings, 'en')
    expect(slideCount(abNone)).toBe(13)
  })

  it('P-RS: a view with a monster VM adds exactly one monster slide', async () => {
    const a = snap('a', 6, new Date('2026-01-01'))
    const first = a.guests[0]
    if (!first) throw new Error('fixture has no VM')
    const withMonster: Snapshot = {
      ...a,
      guests: [...a.guests, { ...first, vmName: 'monster-01', vcpu: cores(32) }],
    }
    const ex = buildExportView(withMonster, [withMonster], MODE, TODAY)
    expect(ex.view.monsters.count).toBeGreaterThan(0)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(14) // 13 baseline + 1 monster

    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.view.monsters.count).toBe(0)
    expect(slideCount(await buildPptx(exNone.view, exNone.trends, strings, 'en'))).toBe(13)
  })

  it('Plan A — snapshotSprawl: a view WITH snapshots adds exactly one slide', async () => {
    const a = snap('a', 3, new Date('2026-01-01'))
    const snapRow: ProxmoxSnapshotRow = {
      node: 'n1',
      guestId: '100',
      guestName: 'Debian',
      guestType: 'qemu',
      name: 'checkpoint-1',
      parent: 'no-parent',
      dateSerial: 46100,
      includeRam: false,
      sizeMib: mib(1024),
    }
    const withSnaps: Snapshot = { ...a, proxmoxSnapshots: [snapRow] }
    const ex = buildExportView(withSnaps, [withSnaps], MODE, TODAY)
    expect(ex.view.snapshotSprawl.count).toBeGreaterThan(0)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(11) // 10 baseline + 1 snapshot sprawl

    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.view.snapshotSprawl.count).toBe(0)
    const abNone = await buildPptx(exNone.view, exNone.trends, strings, 'en')
    expect(slideCount(abNone)).toBe(10)
  })

  it('Plan A — storageContent: a view WITH storage content adds exactly one slide', async () => {
    const a = snap('a', 3, new Date('2026-01-01'))
    const contentRow: ProxmoxStorageContentRow = {
      node: 'n1',
      storage: 'DATA',
      content: 'images',
      fileName: 'disk.qcow2',
      format: 'qcow2',
      sizeMib: mib(10240),
      usagePercent: null,
      guestId: '100',
      guestName: 'Debian',
      creationSerial: null,
    }
    const withContent: Snapshot = { ...a, proxmoxStorageContent: [contentRow] }
    const ex = buildExportView(withContent, [withContent], MODE, TODAY)
    expect(ex.view.storageContent.fileCount).toBeGreaterThan(0)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(11) // 10 baseline + 1 storage content

    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.view.storageContent.fileCount).toBe(0)
    const abNone = await buildPptx(exNone.view, exNone.trends, strings, 'en')
    expect(slideCount(abNone)).toBe(10)
  })

  it('Plan A — clusterHealth: a view WITH HA status adds exactly one slide', async () => {
    const a = snap('a', 3, new Date('2026-01-01'))
    const haStatus: ProxmoxHaStatusRow = {
      id: 'quorum',
      type: 'quorum',
      status: 'OK',
      node: 'n1',
      sid: '',
      state: '',
      crmState: '',
      requestState: '',
      quorate: 'X',
    }
    const withHealth: Snapshot = { ...a, proxmoxHaStatus: [haStatus] }
    const ex = buildExportView(withHealth, [withHealth], MODE, TODAY)
    expect(ex.view.clusterHealth.ha.services.length).toBeGreaterThan(0)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(11) // 10 baseline + 1 cluster health

    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.view.clusterHealth.ha.services.length).toBe(0)
    expect(exNone.view.clusterHealth.ha.managedCount).toBe(0)
    expect(exNone.view.clusterHealth.backups.jobCount).toBe(0)
    const abNone = await buildPptx(exNone.view, exNone.trends, strings, 'en')
    expect(slideCount(abNone)).toBe(10)
  })

  it('Plan A — clusterHealth: a view with HA resources but no status also adds the slide', async () => {
    const a = snap('a', 3, new Date('2026-01-01'))
    const haRes: ProxmoxHaResourceRow = {
      sid: 'vm:100',
      type: 'vm',
      state: 'started',
      group: '',
      failback: '',
      maxRestart: 1,
      maxRelocate: 1,
      comment: '',
    }
    const withRes: Snapshot = { ...a, proxmoxHaResources: [haRes] }
    const ex = buildExportView(withRes, [withRes], MODE, TODAY)
    expect(ex.view.clusterHealth.ha.managedCount).toBeGreaterThan(0)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(11) // 10 baseline + 1 cluster health

    const backupJob: ProxmoxBackupJobRow = {
      id: 'job-1',
      enabled: true,
      all: false,
      vmId: '100,101',
      mode: 'snapshot',
      storage: 'DATA',
      startTime: '02:00',
      schedule: 'daily',
      dayOfWeek: 'mon',
      compress: 'zstd',
      type: 'vzdump',
      node: 'n1',
    }
    const withJob: Snapshot = { ...a, proxmoxBackupJobs: [backupJob] }
    const exJob = buildExportView(withJob, [withJob], MODE, TODAY)
    expect(exJob.view.clusterHealth.backups.jobCount).toBeGreaterThan(0)
    const abJob = await buildPptx(exJob.view, exJob.trends, strings, 'en')
    expect(slideCount(abJob)).toBe(11) // 10 baseline + 1 cluster health
  })

  it('P-HWID: a view with host serials adds exactly one physical-inventory slide', async () => {
    const a = snap('a', 6, new Date('2026-01-01'))
    const withSerials: Snapshot = {
      ...a,
      nodes: a.nodes.map((h, i) => ({ ...h, serialNumber: `SN-${i}` })),
    }
    const ex = buildExportView(withSerials, [withSerials], MODE, TODAY)
    expect(ex.view.hosts.some((h) => h.serialNumber !== '')).toBe(true)
    const ab = await buildPptx(ex.view, ex.trends, strings, 'en')
    expect(slideCount(ab)).toBe(14) // 13 baseline + 1 physical inventory

    // No serials anywhere ⇒ slide omitted (baseline).
    const exNone = buildExportView(a, [a], MODE, TODAY)
    expect(exNone.view.hosts.every((h) => h.serialNumber === '')).toBe(true)
    expect(slideCount(await buildPptx(exNone.view, exNone.trends, strings, 'en'))).toBe(13)
  })

  it('D-01: a 50-cluster view yields exactly 50 cluster slides (no cap)', async () => {
    const a = snap('a', 50, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const ab = await buildPptx(view, trends, strings, 'en')
    // 2 + 50 + storage+network(2) + eos(1) + planned(1) + inventory(1) = 57
    expect(slideCount(ab)).toBe(57)
  })

  it('D-09: a trends-null view produces NO trends slide', async () => {
    const a = snap('a', 4, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    expect(trends).toBeNull()
    const ab = await buildPptx(view, trends, strings, 'en')
    expect(slideCount(ab)).toBe(11) // 2 + 4 + storage+network(2) + eos(1) + planned(1) + inventory(1), no trends
  })

  it('both locales produce a valid same-structure deck (golden, EN + FR)', async () => {
    const a = snap('a', 5, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const en = await buildPptx(view, trends, strings, 'en')
    const fr = await buildPptx(view, trends, strings, 'fr')
    expect(isZip(en)).toBe(true)
    expect(isZip(fr)).toBe(true)
    expect(slideCount(en)).toBe(slideCount(fr)) // locale never changes structure
    expect(slideCount(en)).toBe(12) // 2 + 5 + storage+network(2) + eos(1) + planned(1) + inventory(1)
  })

  it('F-2/F-1: deck carries Storage, Network and Planned slides', async () => {
    const a = snap('a', 3, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const ab = await buildPptx(view, trends, strings, 'en')
    const txt = new TextDecoder('latin1').decode(new Uint8Array(ab))
    expect(txt).toContain('Storage')
    expect(txt).toContain('Network')
    expect(txt).toContain('Planned vs measured estate')
    // 2 + 3 clusters + storage+network(2) + eos(1) + planned(1) + inventory(1)
    expect(slideCount(ab)).toBe(10)
  })

  it('REAL WRITE: a non-null networkPng serializes to a valid OOXML deck (no throw)', async () => {
    // Regression guard for the v2.2.1 export-breaking bug: the network slide
    // used to embed a raw SVG data URI, which throws on a real pptxgenjs write
    // in the browser worker (PowerPoint can't render embedded SVG). The old
    // tests SPIED on addImage and never reached write(), so it shipped. This
    // test produces a REAL PNG and exercises the REAL serialization — assert it
    // RESOLVES and the network slide is present in the output.
    const a = snap('a', 3, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const networkPng = await chartSvgToPng(
      '<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="#0a0"/></svg>',
      40,
      40,
      wasmBytes,
    )
    expect(networkPng[0]).toBe(0x89) // PNG magic — the bytes are a real PNG

    const withPng = await buildPptx(view, trends, strings, 'en', { networkPng })
    expect(isZip(withPng)).toBe(true)
    expect(withPng.byteLength).toBeGreaterThan(1000)
    // Slide count is unchanged vs the note path (the network slide always
    // emits exactly one slide); the win is that write() no longer throws.
    const withNote = await buildPptx(view, trends, strings, 'en')
    expect(slideCount(withPng)).toBe(slideCount(withNote))
    // The embedded PNG media adds real bytes the note path lacks → the PNG deck
    // is strictly larger, proving the image was serialized into the package.
    expect(withPng.byteLength).toBeGreaterThan(withNote.byteLength)
  })

  it('PPT-02: overview + cluster slides surface the previously-dropped facts', async () => {
    const a = snap('a', 3, TODAY)
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const ab = await buildPptx(view, trends, strings, 'en')
    const txt = new TextDecoder('latin1').decode(new Uint8Array(ab))
    // Overview second KPI row
    expect(txt).toContain('Avg CPU %')
    expect(txt).toContain('Physical cores')
    // Storage slide surfaces real datastore usage (cv4pve role breakdown —
    // "Used" replaced the always-zero per-VM "In use").
    expect(txt).toContain('Used')
    // Cluster slide (Phase 18 vsizer-parity rebuild): rich layout.
    // ASCII-only substrings (the zip is latin1-decoded — multibyte
    // em-dash titles like "CPU — mean utilization" won't match here).
    expect(txt).toContain('KEY FIGURES')
    expect(txt).toContain('GHz consumed')
    expect(txt).toContain('GHz available')
    expect(txt).toContain('vCPU allocated')
    expect(txt).toContain('Reserved capacity')
  })
})
