import catalogueData from './catalogue.json'
import { type EosCatalogue, EosCatalogueSchema } from './catalogueSchema'

/**
 * The single parse-once EOS boundary. `catalogue.json` is a committed,
 * build-time snapshot (regenerated by `npm run sync:eos`); it is validated
 * by Zod exactly once here at module scope. Engines downstream
 * (`normalizeOs`, `classifyEsxi`, `bucketEos`) receive this typed value as a
 * parameter and never re-validate or re-read the JSON.
 *
 * Zero runtime network (D-01): the catalogue is a static import. The P1
 * privacy guard throws on any non-same-origin fetch — the only place the
 * third party is ever contacted is the maintainer-run `scripts/sync-eos.mjs`.
 */
const CATALOGUE: EosCatalogue = EosCatalogueSchema.parse(catalogueData)

export function loadEosCatalogue(): EosCatalogue {
  return CATALOGUE
}
