import { describe, expect, it } from 'vitest'
import { bytes, cores, mhz, mib, sockets } from '@/engines/units'
import type { AccountingMode } from '@/types/estate'
import type { GuestRow } from '@/types/guest'
import type { NodeRow } from '@/types/node'
import type { Snapshot } from '@/types/snapshot'
import { buildExportView } from '../buildExportView'
import { assembleHtml } from './assembleHtml'
import { assertSizeBudget } from './inlineAssets'
import { chartToSvg } from './renderCharts'
import { renderReport } from './renderReport'

const TODAY = new Date('2026-01-01T00:00:00Z')
const MODE: AccountingMode = 'configured'
const CLUSTERS = 40

const vmRow = (i: number): GuestRow => ({
  vmName: `vm-${i}`,
  cluster: `C${i % CLUSTERS}`,
  host: `esx-${i % CLUSTERS}`,
  vcpu: cores(4),
  vramMib: mib(8192),
  cpuReadinessPercent: null,
  poweredOn: i % 2 === 0,
  powerState: i % 2 === 0 ? 'poweredOn' : 'poweredOff',
  template: false,
  osConfig: 'Ubuntu Linux (64-bit)',
  osTools: '',
  vmBiosUuid: '',
  vmInstanceUuid: '',
  viSdkUuid: '',
  viSdkServer: '',
  guestType: 'qemu',
  provisionedMib: mib(40_960),
  inUseMib: mib(20_480),
  path: '',
})

const hostRow = (c: number): NodeRow => ({
  hostName: `esx-${c}`,
  cluster: `C${c}`,
  sockets: sockets(2),
  cores: cores(24),
  speedMhz: mhz(2600),
  memoryMib: mib(524_288),
  cpuRatio: 0.4,
  ramRatio: 0.5,
  faultDomain: '',
  model: '',
  vendor: '',
  serialNumber: '',
  esxVersion: '',
})

const estate = (vmCount: number): Snapshot => ({
  id: 'big',
  filename: 'big.xlsx',
  fileSize: bytes(1024),
  capturedAt: new Date('2026-01-01'),
  vCenterLabel: 'vc-prod',
  rvtoolsVersion: '4.7.1.4',
  parsedAt: new Date('2026-01-02'),
  source: 'proxmox',
  viSdkUuid: null,
  vMetaData: [],
  guests: Array.from({ length: vmCount }, (_, i) => vmRow(i)),
  nodes: Array.from({ length: CLUSTERS }, (_, c) => hostRow(c)),
  vmUsage: [],
  proxmoxSnapshots: [],
  proxmoxStorageContent: [],
  proxmoxHaResources: [],
  proxmoxHaStatus: [],
  proxmoxBackupJobs: [],
  storages: [],
  vpartition: [],
  vnetwork: [],
  vswitch: [],
  dvswitch: [],
  dvport: [],
  parseErrors: [],
})

const strings = { 'footer.methodology': 'Generated by vatlas — factual estate synthesis.' }

function build(vmCount: number): string {
  const s = estate(vmCount)
  const { view, trends } = buildExportView(s, [s], MODE, TODAY)
  // discover a real slot id from renderReport (pre-splice) so the chart
  // is injected and the <svg assertion holds
  const body = renderReport({ view, trends, strings, locale: 'en' })
  const firstSlot = body.match(/data-chart-slot="([^"]+)"/)?.[1]
  const charts = new Map<string, string>()
  if (firstSlot) {
    charts.set(
      firstSlot,
      chartToSvg(
        {
          xAxis: { type: 'category', data: ['a', 'b', 'c'] },
          yAxis: { type: 'value' },
          series: [{ type: 'bar', data: [1, 2, 3] }],
        },
        480,
        240,
      ),
    )
  }
  return assembleHtml({ view, trends, charts, strings, locale: 'en' })
}

describe('assembleHtml — single self-contained offline document', () => {
  it('~5000-VM estate is under the 5 MB typical budget', () => {
    const html = build(5000)
    expect(() => assertSizeBudget(html, 'typical')).not.toThrow()
  })

  it('~10000-VM estate is under the 15 MB hard ceiling (HTM-03)', () => {
    const html = build(10_000)
    expect(() => assertSizeBudget(html, 'ceiling')).not.toThrow()
  })

  it('is offline / no-JS safe and a single doctype document (HTM-02)', () => {
    const html = build(2000)
    expect(html.startsWith('<!doctype html')).toBe(true)
    expect(html).toContain('lang="en"')
    expect(html).toContain("default-src 'none'")
    expect(html).toContain('<svg') // chart spliced inline
    expect(html).not.toContain('<script')
    expect(html).not.toContain('<link')
    // No FETCHABLE asset reference (HTM-02 / T-10-10). The inline SVG's
    // `xmlns="http://www.w3.org/2000/svg"` is an inert namespace URI — never
    // fetched, and CSP `default-src 'none'` blocks any fetch regardless — so
    // assert there is no http(s) src/href/url() asset, not merely no "http".
    expect(html).not.toMatch(/(?:src|href)\s*=\s*["']https?:\/\//i)
    expect(html).not.toMatch(/url\(\s*['"]?https?:\/\//i)
  })

  it('unknown chart slots stay empty containers (no raw injection)', () => {
    const s = estate(100)
    const { view, trends } = buildExportView(s, [s], MODE, TODAY)
    const html = assembleHtml({ view, trends, charts: new Map(), strings, locale: 'en' })
    expect(html).toContain('<div class="chart-slot"></div>')
    expect(html).not.toContain('data-chart-slot') // all slots resolved
  })
})
