import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { bytes, cores, mhz, mib, sockets } from '@/engines/units'
import type { AccountingMode } from '@/types/estate'
import type { Snapshot } from '@/types/snapshot'
import type { VHostRow } from '@/types/vhost'
import type { VInfoRow } from '@/types/vinfo'
import { buildExportView } from '../buildExportView'
import { renderReport } from './renderReport'

const TODAY = new Date('2026-01-01T00:00:00Z')
const MODE: AccountingMode = 'configured'

const host = (over: Partial<VHostRow>): VHostRow => ({
  hostName: 'esx-1',
  cluster: 'C1',
  sockets: sockets(2),
  cores: cores(12),
  speedMhz: mhz(2600),
  memoryMib: mib(262_144),
  cpuRatio: 0.3,
  ramRatio: 0.5,
  faultDomain: '',
  model: '',
  vendor: '',
  esxVersion: '',
  ...over,
})

const vm = (over: Partial<VInfoRow>): VInfoRow => ({
  vmName: 'vm-1',
  cluster: 'C1',
  host: 'esx-1',
  vcpu: cores(4),
  vramMib: mib(8192),
  cpuReadinessPercent: null,
  poweredOn: true,
  powerState: 'poweredOn',
  template: false,
  osConfig: 'Ubuntu Linux (64-bit)',
  osTools: '',
  vmBiosUuid: '',
  vmInstanceUuid: '',
  viSdkUuid: '',
  viSdkServer: '',
  provisionedMib: mib(40_960),
  inUseMib: mib(20_480),
  path: '',
  ...over,
})

const snap = (over: Partial<Snapshot>): Snapshot => ({
  id: 's1',
  filename: 'f.xlsx',
  fileSize: bytes(1024),
  capturedAt: new Date('2026-01-01'),
  vCenterLabel: 'vc',
  rvtoolsVersion: '4.7.1.4',
  parsedAt: new Date('2026-01-02'),
  source: 'rvtools',
  viSdkUuid: null,
  vMetaData: [],
  vinfo: [vm({}), vm({ vmName: 'vm-2', cluster: 'C2', host: 'esx-2' })],
  vhost: [host({}), host({ hostName: 'esx-2', cluster: 'C2' })],
  vdatastore: [],
  vpartition: [],
  vnetwork: [],
  vswitch: [],
  dvswitch: [],
  dvport: [],
  parseErrors: [],
  ...over,
})

const strings = { 'footer.methodology': 'Generated by vatlas — factual estate synthesis.' }

const SECTIONS = ['cover', 'headlines', 'per-cluster', 'eos', 'dr', 'annex', 'methodology']

describe('renderReport — HTM-04 sections', () => {
  it('single snapshot: all 7 non-trends sections present, NO trends (D-09)', () => {
    const a = snap({ id: 'a' })
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const html = renderReport({ view, trends, strings, locale: 'en' })
    for (const s of SECTIONS) expect(html).toContain(`data-section="${s}"`)
    expect(html).not.toContain('data-section="trends"')
  })

  it('≥2 snapshots: trends section present in fixed position', () => {
    const a = snap({ id: 'a', capturedAt: new Date('2026-01-01') })
    const b = snap({ id: 'b', capturedAt: new Date('2026-02-01') })
    const { view, trends } = buildExportView(a, [a, b], MODE, TODAY)
    expect(trends).not.toBeNull()
    const html = renderReport({ view, trends, strings, locale: 'en' })
    expect(html).toContain('data-section="trends"')
    // fixed order: trends after dr, before annex
    expect(html.indexOf('data-section="dr"')).toBeLessThan(html.indexOf('data-section="trends"'))
    expect(html.indexOf('data-section="trends"')).toBeLessThan(html.indexOf('data-section="annex"'))
  })
})

describe('renderReport — security', () => {
  it('a cluster name containing a script tag is HTML-escaped (no executable tag)', () => {
    const evil = '<script>alert(1)</script>'
    const a = snap({
      id: 'a',
      vinfo: [vm({ cluster: evil }), vm({ vmName: 'v2', cluster: evil, host: 'esx-2' })],
      vhost: [host({ cluster: evil }), host({ hostName: 'esx-2', cluster: evil })],
    })
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const html = renderReport({ view, trends, strings, locale: 'en' })
    expect(html).not.toContain('<script>alert(1)</script>')
    expect(html).toContain('&lt;script&gt;')
  })

  it('slug-colliding cluster names produce no duplicate id= (Pitfall 6)', () => {
    const a = snap({
      id: 'a',
      vinfo: [vm({ cluster: 'Prod A' }), vm({ vmName: 'v2', cluster: 'Prod/A', host: 'esx-2' })],
      vhost: [host({ cluster: 'Prod A' }), host({ hostName: 'esx-2', cluster: 'Prod/A' })],
    })
    const { view, trends } = buildExportView(a, [a], MODE, TODAY)
    const html = renderReport({ view, trends, strings, locale: 'en' })
    const ids = [...html.matchAll(/id="([^"]+)"/g)].map((m) => m[1])
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('no React raw-markup escape-hatch prop in renderReport source', () => {
    const src = readFileSync(
      join(process.cwd(), 'src/engines/export/html/renderReport.tsx'),
      'utf8',
    )
    // Build the forbidden prop name at runtime so this assertion file does
    // not itself spell the literal token (CLAUDE.md grep-gate trap).
    const forbidden = `dangerously${'Set'}InnerHTML`
    expect(src.includes(forbidden)).toBe(false)
  })
})
